apiVersion: v1
kind: ReplicationController
metadata:
  name: mytomcat-rc
spec:
  replicas: 2
  selector:
    app: mytomcat
    version: 2.7.02
  template:
    metadata:
      labels:
        app: mytomcat
        version: 2.7.02
    spec:
      containers:
      - name: mytomcat-pod
        image: maha4iac/mytomcat:1
        ports:
        - containerPort: 8080
