apiVersion: v1
kind: ReplicationController
metadata:
  name: maha-rc
spec:
  replicas: 3
  selector:
    app: mahanginx
  template:
    metadata:
      labels:
        app: mahanginx
    spec:
      containers:
      - name: maha-pod
        image: nginx
        ports:
        - containerPort: 80
